name: xpert
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.11=hd590300_1
  - anyio=4.3.0=pyhd8ed1ab_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=py310h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - blas=1.1=openblas
  - bleach=6.1.0=pyhd8ed1ab_0
  - boltons=23.1.1=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cached-property=1.5.2=py_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=py310h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=24.3.0=py310h06a4308_0
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.2.0=py310h06a4308_0
  - conda-package-streaming=0.9.0=py310h06a4308_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cuda-version=11.7=h67201e3_3
  - cudatoolkit=11.7.1=h4bc3d14_13
  - cudatoolkit-dev=11.7.0=h1de0b5d_6
  - cudnn=8.9.7.29=hbc23b4c_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.1=py310hc6cd4ac_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=pyhd8ed1ab_0
  - entrypoints=0.4=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.50.0=py310h2372a71_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h4a9f257_0
  - gcc=11.4.0=h7dfb3fc_3
  - gcc_impl_linux-64=11.4.0=h7aa1c59_5
  - gettext=0.21.1=h27087fc_0
  - glib=2.80.0=hf2295e7_1
  - glib-tools=2.80.0=hde27a5a_1
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.22.9=hfa15dee_1
  - gstreamer=1.22.9=h98fc4e7_1
  - gxx=11.4.0=h7dfb3fc_3
  - gxx_impl_linux-64=11.4.0=h7aa1c59_5
  - h11=0.14.0=py310h06a4308_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=8.3.0=h3d44ed6_0
  - hpack=4.0.0=py_0
  - httpcore=1.0.4=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - ipywidgets=8.1.2=py310h06a4308_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py310h06a4308_0
  - json5=0.9.24=pyhd8ed1ab_0
  - jsonpatch=1.33=py310h06a4308_0
  - jsonpointer=2.4=py310hff52083_3
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.21.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py310h06a4308_9
  - jupyter-lsp=2.2.4=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.7.2=py310hff52083_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.13.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.25.4=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=py310h06a4308_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.2=default_h5d6823c_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.6.0=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-devel_linux-64=11.4.0=h922705a_105
  - libgcc-ng=13.2.0=h807b86a_5
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.80.0=hf2295e7_1
  - libgomp=13.2.0=h807b86a_5
  - libgpg-error=1.48=h71f35ed_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.2=h2448989_0
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py310h39ff949_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.2=h33b98f1_1
  - libsanitizer=11.4.0=h4dcbe23_5
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.28=hfc55251_1
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=11.4.0=h922705a_105
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libsystemd0=255=h3516f8a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.6=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h7b6447c_2
  - mamba=1.5.8=py310h51d5547_0
  - markupsafe=2.1.5=py310h2372a71_0
  - matplotlib=3.8.3=py310hff52083_0
  - matplotlib-base=3.8.3=py310h62c0568_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - menuinst=2.0.2=py310h06a4308_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mpg123=1.32.4=h59595ed_0
  - munkres=1.1.4=py_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.3=hd8ed1ab_0
  - nbconvert-core=7.16.3=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.3=hd8ed1ab_0
  - nbformat=5.10.3=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - notebook=7.1.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nspr=4.35=h6a678d5_0
  - nss=3.98=h1d7d5a4_0
  - numpy=1.26.4=py310heeff2f4_0
  - numpy-base=1.26.4=py310h8a23956_0
  - openblas=0.3.26=pthreads_h7a3da1a_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.2.1=hd590300_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandoc=3.1.12.3=ha770c72_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.2.0=py310h01dd4db_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=py310h06a4308_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.8=py310h2372a71_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=py310h06a4308_0
  - python_abi=3.10=2_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - qt-main=5.15.8=h112747c_20
  - qtconsole=5.5.1=py310h06a4308_0
  - qtpy=2.4.1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.34.0=pyhd8ed1ab_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=py310h06a4308_1
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.18.0=py310hcb5633a_0
  - ruamel.yaml=0.18.6=py310h2372a71_0
  - ruamel.yaml.clib=0.2.8=py310h2372a71_0
  - send2trash=1.8.2=py310h06a4308_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sysroot_linux-64=2.12=he073ed8_17
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.2.1=py310h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.4=py310h2372a71_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - truststore=0.8.0=py310h06a4308_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.10=py310h06a4308_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.41=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py310h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - anndata==0.10.6
      - array-api-compat==1.5.1
      - async-timeout==4.0.3
      - cachetools==5.3.3
      - cell-gears==0.0.1
      - click==8.1.7
      - datasets==2.18.0
      - dcor==0.6
      - deprecated==1.2.14
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - filelock==3.13.3
      - flash-attn==1.0.4
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h5py==3.10.0
      - huggingface-hub==0.22.1
      - igraph==0.11.4
      - joblib==1.3.2
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - llvmlite==0.42.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.59.1
      - nvidia-ml-py==12.535.133
      - nvitop==1.3.2
      - pandas==1.5.3
      - patsy==0.5.6
      - protobuf==5.27.2
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pydot==2.0.0
      - pynndescent==0.5.11
      - scanpy==1.9.5
      - scib==1.1.4
      - scikit-learn==1.4.1.post1
      - scikit-misc==0.3.1
      - scipy==1.12.0
      - scperturb==0.1.0
      - seaborn==0.12.2
      - sentry-sdk==2.7.1
      - session-info==1.0.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - termcolor==2.4.0
      - texttable==1.7.0
      - threadpoolctl==3.4.0
      - torch==1.13.0+cu117
      - torch-geometric==2.5.2
      - torchaudio==0.13.0+cu117
      - torchtext==0.14.0
      - torchvision==0.14.0+cu117
      - tzdata==2024.1
      - umap-learn==0.5.5
      - wandb==0.17.3
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
